swagger: "2.0"
info:
  version: 1.0.0
  title: Xpharmacy
  description: our frist project
basePath: /api



consumes:
  - application/json
produces:
  - application/json


definitions:
 
  LoginBody:
    type: object
    title: login
    required:
      - username
      - password
    properties:
      username:
        type: string
        example: no_stress
      password:
        type: string
        example: no_stress
  UserBody:
    type: object
    title: user
    # required:
    #   - username
    #   - password
    properties:
      username:
        type: string
        example: kimoanh
      password:
        type: string
        example: 123456
      phone:
        type: string
        example: 0123456789
      order:
        type: object
        example: 
  Prescription:
    type: object
    title: Prescription
    # required:
    #   - username
    #   - password
    properties:
      image:
        type: string
      phone:
        type: string
        example: 0123456
      createAt:
        type: string
        example: 26-5-2019
      createBy:
        type: string
  
  NewBody:
    type: object
    title: News
    # required:
    #   - username
    #   - password
    properties:
      name:
        type: string
      info:
        type: string
      link: 
        type: string
  
paths:

  /prescription:
    post:
      tags:
        - Prescription
      parameters:
        - name: Drug
          in: body
          description: post
          required: true
          schema:
            $ref: '#/definitions/Prescription'
      responses:
          200:
            description: create the new drug
    get:
      tags:
        - Prescription
      description: get all drug information
      responses:
        200: 
          description: Return all drug
    
  /prescription/{id}:
    get:
      tags:
        - Prescription
      parameters:
        - name: id
          in: path
          required: true
          description: id of drug
          type: string
      responses:
        200:
          description: get drug by id
    put:
      tags:
        - Prescription
      parameters:
        - name: id
          in: path
          required: true
          description: id of drug update
          type: integer
        - name: drug
          in : body 
          description: the drug you want to update 
          required: true
          schema:
            $ref: '#/definitions/Prescription'
      responses:
        200:
          description: The drug has been successfully updated.
          schema:
            $ref: '#/definitions/Prescription'
  /user:
    post:
      summary: "Creat a user"
      tags:
        - User
      parameters:
        - name: user
          in: body
          description: register
          required: true
          schema:
            $ref: "#/definitions/UserBody"
      responses:
          200:
            description: Success resgister user
    get:
      summary: Get all user and paging
      tags:
        - User
      description: get all user information
      responses:
        200: 
          description: Return all users
    
  /user/{id}:
    get:
      summary: Get 1 user
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: id of user
          type: string
      responses:
        200:
          description: get user by id
    put:
      summary: Change user password
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: id of user update
          type: string
        - name: user
          in : body 
          description: the user you want to update 
          required: true
          schema:
            $ref: '#/definitions/UserBody'
      responses:
        200:
          description: The user has been successfully updated.
  /users/{id}/prescriptionImg:
    post:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: id of user post prescription image
          type: string
      responses:
        200: 
          description: Upload complete
  /user/login: 
    post: 
      tags:
        - User
      parameters:
        - name: login
          in: body
          description: login 
          required: true
          schema: 
            $ref: "#/definitions/LoginBody"
      responses:
        200:
          description: Returns all examples
  /user/logout: 
    post: 
      tags:
        - User
      parameters: []
      responses:
        default:
          description: "Successful log out"
          
  /news:
    post:
      tags:
        - News
      parameters:
        - name: news
          in: body
          description: register
          required: true
          schema:
            $ref: "#/definitions/NewBody"
      responses:
          200:
            description: Success post
    
    
  /news/{id}:
    get:
      tags:
        - News
      parameters:
        - name: id
          in: path
          required: true
          description: id of the new 
          type: integer
      responses:
        200:
          description: get the new by id
    put:
      tags:
        - News
      parameters:
        - name: id
          in: path
          required: true
          description: id of the new update
          type: integer
        - name: news
          in : body 
          description: the new you want to update 
          required: true
          schema:
            $ref: '#/definitions/NewBody'
      responses:
        200:
          description: The new has been successfully updated.
          schema:
            $ref: '#/definitions/NewBody'  
  